trigger:
- main 

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: JavaAPI

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Web App'
    appName: 'Black-Mesa-API' 
    appType: webApp
    package: $(Build.ArtifactStagingDirectory)/**/*.jar