trigger:
- main

pool:
  name: Default 

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml' 
    goals: 'package'

- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: AzureWebApp@1
  inputs: 
    azureSubscription: 'Web App'
    appType: 'webAppLinux'
    appName: 'Black-Mesa-API'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
    appServicePlan: 'F1'